replicaCount: 1
image:
  repository: 133845867148.dkr.ecr.eu-west-1.amazonaws.com/api-node-gekko-jenkins
  tag: 5b735eb31c27045bccf40c157374dccee98afcd0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8081
kafka:
  host: kafka-1-cp-kafka-headless:9092
